/* GENERATED by ps2/tools/gen_hw_shadow.py - PS2 shadow of include/nitro/hw.h. See that script. */
#ifndef KH_PS2_NITRO_HW_H_SHADOW
#define KH_PS2_NITRO_HW_H_SHADOW
#include_next "nitro/hw.h"

extern unsigned char kh_ds_io[], kh_ds_pal[], kh_ds_oam[], kh_ds_vram[], kh_ds_hiram[];
volatile void *kh_cp_divcnt_ptr(void);
volatile void *kh_cp_sqrtcnt_ptr(void);

#undef REG_CARD_CONTROL
#define REG_CARD_CONTROL (*(vu32 *)((unsigned int)kh_ds_io + 0x1a4))   /* 0x040001a4 */
#undef REG_DIVCNT
#define REG_DIVCNT (*(vu16 *)kh_cp_divcnt_ptr())   /* 0x04000280: computes results on access */
#undef REG_DIV_NUMER
#define REG_DIV_NUMER (*(vu64 *)((unsigned int)kh_ds_io + 0x290))   /* 0x04000290 */
#undef REG_DIV_DENOM
#define REG_DIV_DENOM (*(vs64 *)((unsigned int)kh_ds_io + 0x298))   /* 0x04000298 */
#undef REG_DIV_RESULT
#define REG_DIV_RESULT (*(vs64 *)((unsigned int)kh_ds_io + 0x2a0))   /* 0x040002a0 */
#undef REG_SQRTCNT
#define REG_SQRTCNT (*(vu16 *)kh_cp_sqrtcnt_ptr())   /* 0x040002b0: computes results on access */
#undef REG_SQRT_RESULT
#define REG_SQRT_RESULT (*(vu32 *)((unsigned int)kh_ds_io + 0x2b4))   /* 0x040002b4 */
#undef REG_SQRT_PARAM
#define REG_SQRT_PARAM (*(u64 *)((unsigned int)kh_ds_io + 0x2b8))   /* 0x040002b8 */
#undef REG_EXMEM_CNT
#define REG_EXMEM_CNT (*(volatile u16 *)((unsigned int)kh_ds_io + 0x204))   /* 0x04000204 */
#undef REG_IF
#define REG_IF (*(volatile u32 *)((unsigned int)kh_ds_io + 0x214))   /* 0x04000214 */
#undef REG_TM0CNT_H
#define REG_TM0CNT_H (*(volatile u16 *)((unsigned int)kh_ds_io + 0x102))   /* 0x04000102 */
#undef REG_TM0CNT_L
#define REG_TM0CNT_L (*(volatile u16 *)((unsigned int)kh_ds_io + 0x100))   /* 0x04000100 */
#undef HW_ROM_HEADER_BUF
#define HW_ROM_HEADER_BUF ((unsigned int)kh_ds_hiram + 0x1fe00)   /* 0x027ffe00 */
#undef HW_CARD_ROM_HEADER
#define HW_CARD_ROM_HEADER ((unsigned int)kh_ds_hiram + 0x1fa80)   /* 0x027ffa80 */
#undef REG_CARDCNT
#define REG_CARDCNT ((unsigned int)kh_ds_io + 0x1a4)   /* 0x040001a4 */
#undef REG_EXMEMCNT_ADDR
#define REG_EXMEMCNT_ADDR ((unsigned int)kh_ds_io + 0x204)   /* 0x04000204 */
#undef REG_IME_ADDR
#define REG_IME_ADDR ((unsigned int)kh_ds_io + 0x208)   /* 0x04000208 */
#undef REG_PAUSE_ADDR
#define REG_PAUSE_ADDR ((unsigned int)kh_ds_io + 0x300)   /* 0x04000300 */
#undef HW_WM_BOOT_BUF
#define HW_WM_BOOT_BUF ((unsigned int)kh_ds_hiram + 0x1fc40)   /* 0x027ffc40 */
#undef REG_DISP3DCNT_ADDR
#define REG_DISP3DCNT_ADDR ((unsigned int)kh_ds_io + 0x60)   /* 0x04000060 */
#undef REG_BG0CNT_ADDR
#define REG_BG0CNT_ADDR ((unsigned int)kh_ds_io + 0x8)   /* 0x04000008 */
#undef REG_BG0OFS_ADDR
#define REG_BG0OFS_ADDR ((unsigned int)kh_ds_io + 0x10)   /* 0x04000010 */
#undef REG_CLEAR_COLOR_ADDR
#define REG_CLEAR_COLOR_ADDR ((unsigned int)kh_ds_io + 0x350)   /* 0x04000350 */
#undef REG_CLEAR_DEPTH_ADDR
#define REG_CLEAR_DEPTH_ADDR ((unsigned int)kh_ds_io + 0x354)   /* 0x04000354 */
#undef REG_CLRIMAGE_OFFSET_ADDR
#define REG_CLRIMAGE_OFFSET_ADDR ((unsigned int)kh_ds_io + 0x356)   /* 0x04000356 */
#undef REG_FOG_COLOR_ADDR
#define REG_FOG_COLOR_ADDR ((unsigned int)kh_ds_io + 0x358)   /* 0x04000358 */
#undef REG_FOG_OFFSET_ADDR
#define REG_FOG_OFFSET_ADDR ((unsigned int)kh_ds_io + 0x35c)   /* 0x0400035c */
#undef REG_EDGE_COLOR_0_L_ADDR
#define REG_EDGE_COLOR_0_L_ADDR ((unsigned int)kh_ds_io + 0x330)   /* 0x04000330 */
#undef REG_FOG_TABLE_0_ADDR
#define REG_FOG_TABLE_0_ADDR ((unsigned int)kh_ds_io + 0x360)   /* 0x04000360 */
#undef REG_MTX_MODE_ADDR
#define REG_MTX_MODE_ADDR ((unsigned int)kh_ds_io + 0x440)   /* 0x04000440 */
#undef REG_POLYGON_ATTR_ADDR
#define REG_POLYGON_ATTR_ADDR ((unsigned int)kh_ds_io + 0x4a4)   /* 0x040004a4 */
#undef REG_TEXIMAGE_PARAM_ADDR
#define REG_TEXIMAGE_PARAM_ADDR ((unsigned int)kh_ds_io + 0x4a8)   /* 0x040004a8 */
#undef REG_TEXPLTT_BASE_ADDR
#define REG_TEXPLTT_BASE_ADDR ((unsigned int)kh_ds_io + 0x4ac)   /* 0x040004ac */
#undef REG_SHININESS_ADDR
#define REG_SHININESS_ADDR ((unsigned int)kh_ds_io + 0x4d0)   /* 0x040004d0 */
#undef REG_END_VTXS_ADDR
#define REG_END_VTXS_ADDR ((unsigned int)kh_ds_io + 0x504)   /* 0x04000504 */
#undef REG_GXSTAT_ADDR
#define REG_GXSTAT_ADDR ((unsigned int)kh_ds_io + 0x600)   /* 0x04000600 */
#undef REG_ALPHA_TEST_REF_ADDR
#define REG_ALPHA_TEST_REF_ADDR ((unsigned int)kh_ds_io + 0x340)   /* 0x04000340 */
#undef HW_LCDC_VRAM
#define HW_LCDC_VRAM ((unsigned int)kh_ds_vram + 0x0)   /* 0x06800000 */
#undef HW_LCDC_VRAM_E
#define HW_LCDC_VRAM_E ((unsigned int)kh_ds_vram + 0x80000)   /* 0x06880000 */
#undef HW_LCDC_VRAM_F
#define HW_LCDC_VRAM_F ((unsigned int)kh_ds_vram + 0x90000)   /* 0x06890000 */
#undef HW_LCDC_VRAM_G
#define HW_LCDC_VRAM_G ((unsigned int)kh_ds_vram + 0x94000)   /* 0x06894000 */
#undef HW_IOREG
#define HW_IOREG ((unsigned int)kh_ds_io + 0x0)   /* 0x04000000 */
#undef HW_COMPONENT_PARAM
#define HW_COMPONENT_PARAM ((unsigned int)kh_ds_hiram + 0x1ff9c)   /* 0x027fff9c */
#undef HW_OAM
#define HW_OAM ((unsigned int)kh_ds_oam + 0x0)   /* 0x07000000 */
#undef HW_PLTT
#define HW_PLTT ((unsigned int)kh_ds_pal + 0x0)   /* 0x05000000 */
#undef HW_MAIN_MEM_SHARED
#define HW_MAIN_MEM_SHARED ((unsigned int)kh_ds_hiram + 0x1f000)   /* 0x027ff000 */
#undef HW_MAIN_MEM_SUB
#define HW_MAIN_MEM_SUB ((unsigned int)kh_ds_hiram + 0x0)   /* 0x027e0000 */
#undef HW_REG_BASE
#define HW_REG_BASE ((unsigned int)kh_ds_io + 0x0)   /* 0x04000000 */
#undef HW_SHARED_ARENA_HI_DEFAULT
#define HW_SHARED_ARENA_HI_DEFAULT ((unsigned int)kh_ds_hiram + 0x1f680)   /* 0x027ff680 */
#undef HW_DTCM_IRQ_STACK_END
#define HW_DTCM_IRQ_STACK_END ((unsigned int)kh_ds_hiram + 0x3f80)   /* 0x027e3f80 */
#undef HW_DTCM_SVC_STACK
#define HW_DTCM_SVC_STACK ((unsigned int)kh_ds_hiram + 0x3f80)   /* 0x027e3f80 */
#undef HW_NVRAM_USER_INFO
#define HW_NVRAM_USER_INFO ((unsigned int)kh_ds_hiram + 0x1fc80)   /* 0x027ffc80 */
#undef HW_MAIN_MEM_SYSTEM
#define HW_MAIN_MEM_SYSTEM ((unsigned int)kh_ds_hiram + 0x1fc00)   /* 0x027ffc00 */
#undef HW_BUTTON_XY_BUF
#define HW_BUTTON_XY_BUF ((unsigned int)kh_ds_hiram + 0x1ffa8)   /* 0x027fffa8 */
#undef REG_TM0CNT_L_ADDR
#define REG_TM0CNT_L_ADDR ((unsigned int)kh_ds_io + 0x100)   /* 0x04000100 */
#undef REG_TM0CNT_H_ADDR
#define REG_TM0CNT_H_ADDR ((unsigned int)kh_ds_io + 0x102)   /* 0x04000102 */
#undef REG_IF_ADDR
#define REG_IF_ADDR ((unsigned int)kh_ds_io + 0x214)   /* 0x04000214 */
#undef REG_DISPCNT_ADDR
#define REG_DISPCNT_ADDR ((unsigned int)kh_ds_io + 0x0)   /* 0x04000000 */
#undef REG_DB_DISPCNT_ADDR
#define REG_DB_DISPCNT_ADDR ((unsigned int)kh_ds_io + 0x1000)   /* 0x04001000 */
#undef HW_VBLANK_COUNT_BUF
#define HW_VBLANK_COUNT_BUF ((unsigned int)kh_ds_hiram + 0x1fc3c)   /* 0x027ffc3c */
#undef REG_DIVCNT_ADDR
#define REG_DIVCNT_ADDR ((unsigned int)kh_ds_io + 0x280)   /* 0x04000280 */
#undef REG_DIV_NUMER_ADDR
#define REG_DIV_NUMER_ADDR ((unsigned int)kh_ds_io + 0x290)   /* 0x04000290 */
#undef REG_DIV_DENOM_ADDR
#define REG_DIV_DENOM_ADDR ((unsigned int)kh_ds_io + 0x298)   /* 0x04000298 */
#undef REG_DIV_RESULT_ADDR
#define REG_DIV_RESULT_ADDR ((unsigned int)kh_ds_io + 0x2a0)   /* 0x040002a0 */
#undef REG_BG1CNT_ADDR
#define REG_BG1CNT_ADDR ((unsigned int)kh_ds_io + 0xa)   /* 0x0400000a */
#undef REG_BG2CNT_ADDR
#define REG_BG2CNT_ADDR ((unsigned int)kh_ds_io + 0xc)   /* 0x0400000c */
#undef REG_BG3CNT_ADDR
#define REG_BG3CNT_ADDR ((unsigned int)kh_ds_io + 0xe)   /* 0x0400000e */
#undef REG_DB_BG0CNT_ADDR
#define REG_DB_BG0CNT_ADDR ((unsigned int)kh_ds_io + 0x1008)   /* 0x04001008 */
#undef REG_DB_BG1CNT_ADDR
#define REG_DB_BG1CNT_ADDR ((unsigned int)kh_ds_io + 0x100a)   /* 0x0400100a */
#undef REG_DB_BG2CNT_ADDR
#define REG_DB_BG2CNT_ADDR ((unsigned int)kh_ds_io + 0x100c)   /* 0x0400100c */
#undef REG_DB_BG3CNT_ADDR
#define REG_DB_BG3CNT_ADDR ((unsigned int)kh_ds_io + 0x100e)   /* 0x0400100e */
#undef HW_BG_PLTT
#define HW_BG_PLTT ((void *)((unsigned int)kh_ds_pal + 0x0))   /* 0x05000000 */
#undef HW_DB_BG_PLTT
#define HW_DB_BG_PLTT ((void *)((unsigned int)kh_ds_pal + 0x400))   /* 0x05000400 */

#endif
