/* PS2 override: player overlays are native code at distinct addresses.
 *
 * On DS each of the four RAM slots has one fixed entry address; loading a player overlay
 * replaces the code at that address.  The static PS2 ELF instead dispatches by the actual
 * overlay ID through the registry generated by gen_link.py.
 */
#include "game/engine.h"

typedef struct { int overlayId[4]; } OverlayGroup;

extern OverlayGroup data_ov029_020b30b0[];
extern int data_ov029_020b3200[4];
extern int data_ov029_020b320c[];
extern int kh_overlay_call_entry(unsigned int id);
extern void OS_Terminate(void);

int Ov029_AcquireOverlaySlot(int proc, int group)
{
    int loaded = -1;
    int *slot = data_ov029_020b320c;
    int *cand = &data_ov029_020b30b0[group].overlayId[3];
    int k = 3;
    (void)proc;

    do {
        if (*slot == -1 && *cand != -1) {
            loaded = data_ov029_020b30b0[group].overlayId[k];
            data_ov029_020b3200[k] = loaded;
            break;
        }
        slot--;
        cand--;
        k--;
    } while (k >= 0);

    if (loaded < 0) {
        OS_Terminate();
        return -1;
    }

    LoadOverlaySync(0, loaded);
    if (!kh_overlay_call_entry((unsigned int)loaded)) {
        OS_Terminate();
        return -1;
    }
    return loaded;
}
