#!/usr/bin/env python3
"""Turn the prototype audit into the ABI variant table used by prep_sources.py (rule R3).

    python ps2/tools/proto_audit.py      # slow: compiles every source with -aux-info
    python ps2/tools/abi_variants.py     # writes ps2/config/abi_variants.txt (committed)

RULES maps (function, return-kind, parameter-kinds) of a *caller's* declaration to the symbol
that caller must use on the EE.  The variants are implemented in ps2/src/abi/.  Declarations
that are harmless under n32 (a 64-bit return only ever truncated to int, extra ignored
arguments) are deliberately not listed; see docs/PS2_PORT.md, "Compiler portability".
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import ps2cfg  # noqa: E402

S = "32"
L = "64"
P = "p"

RULES = {
    # CodeWarrior runtime: quotient in r0, remainder in r1; read as long long = q | r << 32
    "func_02020400": {(L, (S, S)): "kh_rt_s32_divmod"},            # _s32_div_f
    "Math_DivMod": {(L, (S, S)): "kh_rt_u32_divmod"},              # _u32_div_f
    # _ll_udiv(u64 num, u64 den): some callers pass den as two words, or num too
    "func_02020368": {
        (S, (L, S, S)): "kh_rt_ll_udiv_w_32",
        (L, (L, S, S)): "kh_rt_ll_udiv_w",
        (L, (S, S, S, S)): "kh_rt_ll_udiv_ww",
    },
    # game functions taking one 64-bit parameter that some callers pass as lo, hi words
    "Ov002_AddPanelCounter": {(S, (L, S, S)): "Ov002_AddPanelCounter__ll"},
    "Ov002_ArmShake": {("v", (L,)): "Ov002_ArmShake__ll"},
}
for n in ("Ov156_GroundSweep", "Ov157_GroundSweep", "Ov191_BoxSweepPush", "Ov192_BoxSweepPush", "Ov193_BoxSweepPush"):
    RULES[n] = {("v", (P, S, S, P)): n + "__w"}
for ov in ("000", "004", "005", "008", "009", "025", "069"):
    n = f"Ov{ov}_FoldPanelIntoTally"
    RULES[n] = {("v", (P, S, S, S, P)): n + "__w"}


def main():
    audit = json.load(open(os.path.join(ps2cfg.ROOT, "build", "ps2", "proto_audit.json")))
    lines = ["# GENERATED by ps2/tools/abi_variants.py from the prototype audit - do not edit by hand.",
             "# <function> <variant symbol> <caller source>...", ""]
    missing = []
    for fn, rules in sorted(RULES.items()):
        if fn not in audit:
            missing.append(fn)
            continue
        for v in audit[fn]["variants"]:
            key = (v["ret"], tuple(v["params"]))
            if key in rules:
                lines.append(f"{fn} {rules[key]} " + " ".join(v["files"]))
    out = os.path.join(ps2cfg.ROOT, "ps2", "config", "abi_variants.txt")
    open(out, "w", newline="\n").write("\n".join(lines) + "\n")
    print(f"wrote {out}: {len(lines) - 3} rules" + (f"; not in audit: {missing}" if missing else ""))


if __name__ == "__main__":
    main()
