#!/usr/bin/env python3
"""Generate ps2/include/nitro/hw.h, the PS2 shadow of the SDK's include/nitro/hw.h.

The SDK header defines the DS memory map and register macros with raw addresses:
    #define REG_DIVCNT   (*(vu16 *)0x04000280)        register lvalue
    #define HW_ROM_HEADER_BUF 0x027ffe00               address constant
Sources that include it would reach those addresses without any literal of their own, so
prep_sources.py and the library scan would not see them.  The shadow (found first through
-I ps2/include) includes the original and redefines every such macro the way prep rule R5 maps
literals:
  * display/2D state, divider/sqrt operands, palette, OAM, VRAM, DTCM/shared area -> the PS2
    state blocks (kh_ds_io, kh_ds_pal, kh_ds_oam, kh_ds_vram, kh_ds_hiram);
  * geometry-engine register lvalues -> a compile error: their stores must become
    kh_ge_port_write1() (prep rule R8 knows these names via hw_registers()), so any use R8 did
    not convert fails loudly instead of silently dropping 3D commands;
  * geometry register *address* constants (REG_*_ADDR) -> kh_ds_io offsets, which
    MIi_CpuSend32 routes to the geometry front end.

    python ps2/tools/gen_hw_shadow.py
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import ps2cfg  # noqa: E402

ROOT = ps2cfg.ROOT
REGIONS = [
    (0x04000000, 0x04001100, "kh_ds_io"),
    (0x05000000, 0x05000800, "kh_ds_pal"),
    (0x07000000, 0x07000800, "kh_ds_oam"),
    (0x06800000, 0x068a4000, "kh_ds_vram"),
    (0x027e0000, 0x02800000, "kh_ds_hiram"),
]
GEOMETRY = (0x04000400, 0x04000700)
# Divider / square-root control registers: every access (the busy-wait read that always precedes
# reading a result) first computes the results from the operands in the state block, so code
# that reads DIV_RESULT / SQRT_RESULT through these macros sees the exact hardware values.
COMPUTING = {0x04000280: "kh_cp_divcnt_ptr", 0x040002b0: "kh_cp_sqrtcnt_ptr"}
LVALUE = re.compile(r"^\s*#\s*define\s+(\w+)\s+\(\s*\*\s*\(\s*([\w ]+?)\s*\*\s*\)\s*\(?\s*(0x[0-9a-fA-F]+)[uUlL]*\s*\)?\s*\)\s*$", re.M)
CONST = re.compile(r"^\s*#\s*define\s+(\w+)\s+\(?\s*(0x[0-9a-fA-F]+)[uUlL]*\s*\)?\s*$", re.M)
# address constants with a pointer cast: `#define HW_BG_PLTT ((void *)0x05000000)`
CAST = re.compile(r"^\s*#\s*define\s+(\w+)\s+\(\s*\(\s*([\w ]+?\*)\s*\)\s*(0x[0-9a-fA-F]+)[uUlL]*\s*\)\s*$", re.M)


def region(v):
    for a, b, base in REGIONS:
        if a <= v < b:
            return base, v - a
    return None


def hw_registers():
    """{macro name: (address, is_lvalue)} of the SDK header's register/address macros."""
    text = open(os.path.join(ROOT, "include", "nitro", "hw.h"), encoding="utf-8").read()
    out = {}
    for m in LVALUE.finditer(text):
        out[m.group(1)] = (int(m.group(3), 16), True)
    for m in CONST.finditer(text):
        if m.group(1) not in out:
            out[m.group(1)] = (int(m.group(2), 16), False)
    return out


def main():
    text = open(os.path.join(ROOT, "include", "nitro", "hw.h"), encoding="utf-8").read()
    lines = ["/* GENERATED by ps2/tools/gen_hw_shadow.py - PS2 shadow of include/nitro/hw.h. See that script. */",
             "#ifndef KH_PS2_NITRO_HW_H_SHADOW", "#define KH_PS2_NITRO_HW_H_SHADOW", '#include_next "nitro/hw.h"', "",
             "extern unsigned char kh_ds_io[], kh_ds_pal[], kh_ds_oam[], kh_ds_vram[], kh_ds_hiram[];",
             "volatile void *kh_cp_divcnt_ptr(void);", "volatile void *kh_cp_sqrtcnt_ptr(void);", ""]
    n = 0
    for m in LVALUE.finditer(text):
        name, typ, v = m.group(1), m.group(2), int(m.group(3), 16)
        r = region(v)
        if not r:
            continue
        lines.append(f"#undef {name}")
        if GEOMETRY[0] <= v < GEOMETRY[1]:
            lines.append(f"#define {name} KH_PS2_geometry_register_{name}_must_go_through_kh_ge_port_write1")
        elif v in COMPUTING:
            lines.append(f"#define {name} (*({typ} *){COMPUTING[v]}())   /* 0x{v:08x}: computes results on access */")
        else:
            lines.append(f"#define {name} (*({typ} *)((unsigned int){r[0]} + 0x{r[1]:x}))   /* 0x{v:08x} */")
        n += 1
    seen = {m.group(1) for m in LVALUE.finditer(text)}
    for m in CONST.finditer(text):
        name, v = m.group(1), int(m.group(2), 16)
        if name in seen:
            continue
        r = region(v)
        if not r:
            continue
        lines.append(f"#undef {name}")
        lines.append(f"#define {name} ((unsigned int){r[0]} + 0x{r[1]:x})   /* 0x{v:08x} */")
        n += 1
    for m in CAST.finditer(text):
        name, typ, v = m.group(1), m.group(2), int(m.group(3), 16)
        r = region(v)
        if name in seen or not r:
            continue
        lines.append(f"#undef {name}")
        lines.append(f"#define {name} (({typ})((unsigned int){r[0]} + 0x{r[1]:x}))   /* 0x{v:08x} */")
        n += 1
    lines += ["", "#endif", ""]
    os.makedirs(os.path.join(ROOT, "ps2", "include", "nitro"), exist_ok=True)
    open(os.path.join(ROOT, "ps2", "include", "nitro", "hw.h"), "w", newline="\n").write("\n".join(lines))
    print(f"ps2/include/nitro/hw.h: {n} macros redefined")


if __name__ == "__main__":
    main()
